baseurl: ""
url: "https://chiefpansancolt.live"

permalink: simple
timezone: America/New_York

pagination:
  enabled: true
  per_page: 6

collections:
  clips:
    output: true
    name: Clips
  pops:
    output: true
    name: Pops
    sort_by: group
  documentation:
    output: true
    name: Documentation

defaults:
  - scope:
      path: _posts
    values:
      layout: post
      category: posts
  - scope:
      path: "assets/images"
    values:
      image: true

svg:
  optimize: true