baseurl: ""
url: "https://chiefpansancolt.live"

permalink: simple
timezone: America/New_York

pagination:
  enabled: true
  per_page: 2

collections:
  clips:
    output: true
    name: Clips
  documentation:
    output: true
    name: Documentation

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

svg:
  optimize: true