name: Lints

on: [push]

jobs:
  javascript:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: eslint
      uses: reviewdog/action-eslint@v1.9.0
      with:
        reporter: github-check
        eslint_flags: 'frontend/'