name: Lints

on: [push]

jobs:
  javascript:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: eslint
      uses: reviewdog/action-eslint@v1.9.0
      with:
        reporter: github-check
        eslint_flags: 'frontend/'
        fail_on_error: true
  
  css:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.4.4
      with:
        node-version: '14'
    - name: install dependencies
      run: npm install
    - name: stylelint
      uses: reviewdog/action-stylelint@v1.7.0
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-check
        stylelint_input: 'frontend/**/*.css'

  markdown:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: stylelint
      uses: prologic/action-markdownlint@v0.1
      with:
        reporter: github-check